### ISSUE TITLE
Cannot access file 

### ISSUE THREAD

**Issue by kaciula** [flutter-cavalry/accessing_security_scoped_resource#1]
Hi. When tapping on a file with a custom extension on iOS (that I registered as a type in Xcode), my Flutter app gets triggered and opened and I receive a file url such as this: `file:///private/var/mobile/Containers/Shared/AppGroup/1822654E-3DCE-480F-9C5E-BEF214FEAFC6/File%20Provider%20Storage/DAVIRW_240120_09-13-39.protern`

I'm calling you start method before trying to work with the file but I still get an error that the file does not exist. Any idea why?

**Comment by mgenware** [comment]
Are you using the URL version of the API `startAccessingSecurityScopedResourceWithURL` (not the file path version)? If yes, sorry I have no clue why it happens as my knowledge of this API is limited to working with icloud directories :-)

**Comment by kaciula** [comment]
@mgenware I figured out the issue. I first needed to call Uri.decodeFull().
